<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TematicaRepository extends EntityRepository
{
	public function findByName($nombre)
	{
	   $em = $this->getEntityManager();
	   $query = $em->createQuery('select tem from AppBundle:Tematica tem where tem.nombre LIKE :nombre order by tem.nombre')
		->setParameter('nombre', '%'.$nombre.'%');
	   return $query->getResult(); 
	}
}
